# The model is to be tested with different images to know if it is working correctly.

Import the packages and load the saved model
Import the required libraries

In [11]:
!pip install Tensorflow
!pip install keras
!pip install pillow

In [12]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array
import numpy as np

In [13]:
model=load_model("fruit.h5")

Load the test image, pre-process it and predict
Pre-processing the image includes converting the image to array and resizing according to the model. 
Give the pre-processed image to the model to know to which class your model belongs to.

In [18]:
img=image.load_img('C:/Users/Dell/Desktop/Dataset Plant Disease/fruit-dataset/fruit-dataset/test/Apple___healthy/21c10a73-ebeb-4a16-898b-8b39d9d6eca2___RS_HL 6315.jpg', target_size=(128,128))

In [19]:
x=image.img_to_array(img)

In [20]:
x=np.expand_dims(x,axis=0)

In [22]:
x

array([[[[123., 117., 117.],
         [117., 111., 111.],
         [121., 115., 115.],
         ...,
         [125., 119., 119.],
         [122., 116., 116.],
         [132., 126., 126.]],

        [[125., 119., 119.],
         [121., 115., 115.],
         [126., 120., 120.],
         ...,
         [124., 118., 118.],
         [119., 113., 113.],
         [135., 129., 129.]],

        [[121., 115., 115.],
         [119., 113., 113.],
         [127., 121., 121.],
         ...,
         [112., 106., 106.],
         [123., 117., 117.],
         [117., 111., 111.]],

        ...,

        [[165., 164., 169.],
         [163., 162., 167.],
         [162., 161., 166.],
         ...,
         [175., 174., 180.],
         [176., 175., 181.],
         [177., 176., 182.]],

        [[164., 163., 168.],
         [163., 162., 167.],
         [166., 165., 170.],
         ...,
         [176., 175., 181.],
         [179., 178., 184.],
         [182., 181., 187.]],

        [[163., 162., 167.],
       

In [23]:
y=np.argmax(model.predict(x), axis=1)

In [38]:
y

array([3], dtype=int64)

In [27]:
index=['Apple___Black_rot', 'Apple___healthy', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 
'Peach___Bacterial_spot',  'Peach___healthy']

In [28]:
index[y[0]]

'Apple___healthy'

In [33]:
img=image.load_img('C:/Users/Dell/Desktop/Dataset Plant Disease/fruit-dataset/fruit-dataset/test/Peach___Bacterial_spot/0a05b466-12ed-4ef3-935c-ea7e73107705___Rut._Bact.S 3353.jpg',  target_size=(128,128))

In [35]:
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
y=np.argmax(model.predict(x), axis=1)

In [40]:
index[y[0]]

'Corn_(maize)___healthy'

In [41]:
y

array([3], dtype=int64)