# The model is to be tested with different images to know if it is working correctly.

Import the packages and load the saved model
Import the required libraries

In [1]:
!pip install Tensorflow
!pip install keras
!pip install pillow

In [2]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import img_to_array
import numpy as np

In [3]:
model=load_model("vegetable.h5")

Load the test image, pre-process it and predict
Pre-processing the image includes converting the image to array and resizing according to the model. 
Give the pre-processed image to the model to know to which class your model belongs to.

In [12]:
img=image.load_img('C:/Users/Dell/Desktop/Dataset Plant Disease/Veg-dataset/Veg-dataset/test_set/Pepper,_bell___healthy/b61a5e27-1da3-4c61-9951-691fdceb9e81___JR_HL 8744.jpg', target_size=(128,128))

In [13]:
x=image.img_to_array(img)

In [14]:
x=np.expand_dims(x,axis=0)

In [15]:
x

array([[[[151., 136., 141.],
         [163., 148., 153.],
         [148., 133., 138.],
         ...,
         [161., 149., 153.],
         [160., 148., 152.],
         [164., 152., 156.]],

        [[150., 135., 140.],
         [146., 131., 136.],
         [147., 132., 137.],
         ...,
         [157., 145., 149.],
         [162., 150., 154.],
         [169., 157., 161.]],

        [[152., 137., 142.],
         [154., 139., 144.],
         [149., 134., 139.],
         ...,
         [162., 150., 154.],
         [161., 149., 153.],
         [154., 142., 146.]],

        ...,

        [[146., 134., 138.],
         [132., 120., 124.],
         [125., 113., 117.],
         ...,
         [153., 142., 148.],
         [200., 189., 195.],
         [154., 143., 149.]],

        [[152., 140., 144.],
         [149., 137., 141.],
         [145., 133., 137.],
         ...,
         [188., 177., 183.],
         [153., 142., 148.],
         [184., 173., 179.]],

        [[120., 108., 112.],
       

In [16]:
y=np.argmax(model.predict(x), axis=1)

In [17]:
y

array([1], dtype=int64)

In [18]:
index=['Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot']

In [19]:
index[y[0]]

'Pepper,_bell___healthy'

In [31]:
img=image.load_img('C:/Users/Dell/Desktop/Dataset Plant Disease/Veg-dataset/Veg-dataset/test_set/Tomato___Septoria_leaf_spot/c680ff81-bb1f-48c3-a68d-50ba12a94392___Matt.S_CG 7419.jpg',  target_size=(128,128))

In [32]:
x=image.img_to_array(img)
x=np.expand_dims(x,axis=0)
y=np.argmax(model.predict(x), axis=1)

In [33]:
index=['Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot']

In [34]:
index[y[0]]

'Tomato___Septoria_leaf_spot'

In [35]:
y

array([8], dtype=int64)